recipe: default.v1
language: fa
pipeline:
- name: WhitespaceTokenizer 
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: rasa/LaBSE
  cache_dir: null
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.2
#    ambiguity_threshold: 0.1
  # This part is for chitchat and faq intent handling (retrieval intent)
  # See https://rasa.com/docs/rasa/chitchat-faqs/
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq
- name: ResponseSelector
  epochs: 100
  retrieval_intent: chitchat
policies:
- name: RulePolicy
assistant_id: 20230330-050721-brass-banner
